SandBox-2/force-app/main/default/objects/IMS_Monthly_Stats__c/IMS_Monthly_Stats__c.object-meta.xml
<CustomObject>
    <label>IMS Monthly Stats</label>
    <nameField>
        <displayFormat>MDN-{000000}</displayFormat>
        <label>MDN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Monthly Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/IMS_Monthly_Stats__c/fields/FORMULA_Year__c.field-meta.xml
<CustomField>
    <fullName>FORMULA_Year__c</fullName>
    <formula>IMS_Year__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year (hidden)</label>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/IMS_Monthly_Stats__c/fields/IMS_Year__c.field-meta.xml
<CustomField>
    <fullName>IMS_Year__c</fullName>
    <label>IMS Year</label>
    <referenceTo>IMS_Yearly_Stats__c</referenceTo>
    <relationshipLabel>IMS Monthly Stats</relationshipLabel>
    <relationshipName>IMS_Monthly_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/IMS_Yearly_Stats__c/IMS_Yearly_Stats__c.object-meta.xml
<CustomObject>
    <label>IMS Yearly Stats</label>
    <nameField>
        <displayFormat>YDN-{0000}</displayFormat>
        <label>YDN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Yearly Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/IMS_Yearly_Stats__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IMS Yearly Stats</relationshipLabel>
    <relationshipName>IMS_Yearly_Stats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Production/force-app/main/default/objects/IMS_Yearly_Stats__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/IMSHelper.cls
public class IMSHelper {
    public static void createIMSYear(List<Account> accounts){
        List<IMS_Yearly_Stats__c> imsYearsToCreate = new List<IMS_Yearly_Stats__c>();
        String year = system.now().format('YYYY');

        //build map of duplicates
        Map<Id, String> accountYearMap = new Map<Id, String>();
        for (IMS_Yearly_Stats__c imsYear : [select Id, Account__c, Year__c
                                            FROM IMS_Yearly_Stats__c 
                                            WHERE Year__c =: year]){
        	accountYearMap.put(imsYear.Account__c, imsYear.Year__c);
        }

        
        for (Account a : accounts){
            if(accountYearMap.containsKey(a.Id) && accountYearMap.get(a.Id) == year){                
                system.debug('### IMS Year [' + year + '] already exists for Account [' + a.Id +']');
            }
            else{
                system.debug('### IMSHelper Creating IMS Year [' + year + ']  for Account [' + a.Id +']');
                imsYearsToCreate.add(new IMS_Yearly_Stats__c(Year__c = year,
                                                             Account__c = a.Id));
            }
        }
        
        if (!imsYearsToCreate.isEmpty()){
            insert imsYearsToCreate;
        }
        
    }
    public static void createPreviousIMSMonth(List<IMS_Yearly_Stats__c > imsYears){
        List<IMS_Monthly_Stats__c> imsMonthsToCreate = new List<IMS_Monthly_Stats__c>();
        String month = system.now().addMonths(-1).format('MMMMM');
        String year = system.now().format('YYYY');
        
        //build map of duplicates
        Map<Id, String> yearMonthMap = new Map<Id, String>();
        for (IMS_Monthly_Stats__c imsMonth : [select Id, IMS_Year__c, FORMULA_Year__c, Month__c 
                                              FROM IMS_Monthly_Stats__c 
                                              WHERE FORMULA_Year__c =: year AND Month__c =: month]){
            yearMonthMap.put(imsMonth.IMS_Year__c, imsMonth.Month__c);
        }
        
        
        for (IMS_Yearly_Stats__c imsYear : imsYears){
            if(yearMonthMap.containsKey(imsYear.Id) && yearMonthMap.get(imsYear.Id) == month){
                system.debug('### IMSHelper IMS Month [' + month + '] already exists for Year [' + year +'] for Account [' + imsYear.Account__c +']');
            }
            else{
                system.debug('### IMSHelper Creating IMS Month [' + month + '] for Year [' + year +'] for Account [' + imsYear.Account__c +']');
                imsMonthsToCreate.add(new IMS_Monthly_Stats__c (IMS_Year__c = imsYear.Id,
                                                                Month__c = month));
            }
        }
        
        if(!imsMonthsToCreate.isEmpty()){
            insert imsMonthsToCreate;
        }
    }
}