Production/force-app/main/default/objects/Case/fields/Sales_Planner_History__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Planner History</label>
    <referenceTo>Sales_Planner_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <formula>Account_Sales_Planner__r.Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner</label>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Strategic Actions :</label>
    <type>TextArea</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <formula>Account_Sales_Planner__r.DDD_Outlet_ID__c</formula>
    <label>DDD Outlet ID</label>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/H_RAM_Projected_Vaxchora_2__c.field-meta.xml
<CustomField>
    <fullName>H_RAM_Projected_Vaxchora_2__c</fullName>
    <label>2H RAM Vaxchora Projected Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Issues_Objections_Limitations__c.field-meta.xml
<CustomField>
    <fullName>Issues_Objections_Limitations__c</fullName>
    <label>Key Issues/Constraints:</label>
    <type>TextArea</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Personal Note</label>
    <type>TextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <formula>Account_Sales_Planner__r.Outlet_Name__c</formula>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Personal_Note__c.field-meta.xml
<CustomField>
    <fullName>Personal_Note__c</fullName>
    <formula>Account_Sales_Planner__r.Personal_Note__c</formula>
    <label>Personal Note</label>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Pricing_Discount_Programs__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Discount_Programs__c</fullName>
    <description>2019 Pricing Discount Programs</description>
    <inlineHelpText>Based on Signed Contract</inlineHelpText>
    <label>Pricing Discount Programs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3FOR30NORETURNS</fullName>
            </value>
            <value>
                <fullName>GOLD19NORETURNS</fullName>
            </value>
            <value>
                <fullName>GOLD+19NORETURNS</fullName>
            </value>
            <value>
                <fullName>PURPLE19NORETURNS</fullName>
            </value>
            <value>
                <fullName>PURPLE+19NORETURNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Total_F2F_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Total_F2F_Meetings__c</fullName>
    <label>CY Total F2F Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Vivotif_Committed_Doses__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Committed_Doses__c</fullName>
    <description>2019 Vivotif Contract program</description>
    <label>Vivotif Committed Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/X1H_Actual_Vaxchora_Doses__c.field-meta.xml
<CustomField>
    <fullName>X1H_Actual_Vaxchora_Doses__c</fullName>
    <formula>Account_Sales_Planner__r.X1H_Actual_Vaxchora_Doses__c</formula>
    <label>1H- Actual Vaxchora Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/X1H_Vaxchora_Gap__c.field-meta.xml
<CustomField>
    <fullName>X1H_Vaxchora_Gap__c</fullName>
    <formula>Account_Sales_Planner__r.X1H_Actual_Vaxchora_Doses__c-H_RAM_Projected_Vaxchora_1__c</formula>
    <label>1H Vaxchora Gap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/X2019_TotalActivities__c.field-meta.xml
<CustomField>
    <fullName>X2019_TotalActivities__c</fullName>
    <label>CY Total  Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/X2H_Actual_Vaxchora_Doses__c.field-meta.xml
<CustomField>
    <fullName>X2H_Actual_Vaxchora_Doses__c</fullName>
    <formula>Account_Sales_Planner__r.X2H_Actual_Vaxchora_Doses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2H- Actual Vaxchora Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/X2H_Vaxchora_Gap__c.field-meta.xml
<CustomField>
    <fullName>X2H_Vaxchora_Gap__c</fullName>
    <formula>Account_Sales_Planner__r.X2H_Actual_Vaxchora_Doses__c-H_RAM_Projected_Vaxchora_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2H Vaxchora Gap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/Sales_Planner_History__c.object-meta.xml
<CustomObject>
    <label>Sales Planner History</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlannersHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <label>Account Owner</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/Account_Sales_Planner_History__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlannersHistory</relationshipLabel>
    <relationshipName>SalesPlannersHistory</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <inlineHelpText>Dual Product Loyal:Reorders of Vaxchora and ^25% Vivotif Mkt Share	 
Vaxchora Supporter:Re-ordering Vaxchora; little or no Vivotif usage.  Vivotif Supporter:^25% Vivotif Market Share, and no Vaxchora Usage. Travel Vaccinator	Vaccinate travelers,</inlineHelpText>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual Product Loyal</fullName>
            </value>
            <value>
                <fullName>Vaxchora Supporter</fullName>
            </value>
            <value>
                <fullName>Vivotif Supporter</fullName>
            </value>
            <value>
                <fullName>Travel Vaccinator</fullName>
            </value>
            <value>
                <fullName>PaxVax Naïve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Strategic Actions :</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Contract_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Date__c</fullName>
    <description>2019 Pricing Program</description>
    <inlineHelpText>Based on signed contract</inlineHelpText>
    <label>Contract Signed Date</label>
    <type>Date</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/H_RAM_Projected_Vaxchora_1__c.field-meta.xml
<CustomField>
    <fullName>H_RAM_Projected_Vaxchora_1__c</fullName>
    <label>1H RAM Vaxchora Projected Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Issues_Objections_Limitations__c.field-meta.xml
<CustomField>
    <fullName>Issues_Objections_Limitations__c</fullName>
    <label>Key Issues/Constraints:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Personal_Note__c.field-meta.xml
<CustomField>
    <fullName>Personal_Note__c</fullName>
    <label>Personal Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Sales_Planner_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Id__c</fullName>
    <label>Old Sales Planner Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Total_F2F_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Total_F2F_Meetings__c</fullName>
    <label>2019 Total F2F Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/Unique_SalesPlanner__c.field-meta.xml
<CustomField>
    <fullName>Unique_SalesPlanner__c</fullName>
    <label>Unique SalesPlanner</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Vaxchora_Doses_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_Doses_Commitment__c</fullName>
    <description>2019 Pricing Program</description>
    <inlineHelpText>Based on signed contract</inlineHelpText>
    <label>Vaxchora Doses Commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Vaxchora_Ordered_Doses__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_Ordered_Doses__c</fullName>
    <description>2019 Pricing Program</description>
    <inlineHelpText>Based on daily sales report.</inlineHelpText>
    <label>Vaxchora Ordered Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/Vivotif_Committed_Doses__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Committed_Doses__c</fullName>
    <label>Vivotif Committed Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/X1H_Actual_Vaxchora_Doses__c.field-meta.xml
<CustomField>
    <fullName>X1H_Actual_Vaxchora_Doses__c</fullName>
    <label>1H- Actual Vaxchora Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/X1H_Vaxchora_Gap__c.field-meta.xml
<CustomField>
    <fullName>X1H_Vaxchora_Gap__c</fullName>
    <label>1H Vaxchora Gap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/X2019_TotalActivities__c.field-meta.xml
<CustomField>
    <fullName>X2019_TotalActivities__c</fullName>
    <label>2019 Total  Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner_History__c/fields/X2H_Actual_Vaxchora_Doses__c.field-meta.xml
<CustomField>
    <fullName>X2H_Actual_Vaxchora_Doses__c</fullName>
    <label>2H- Actual Vaxchora Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner_History__c/fields/X2H_Vaxchora_Gap__c.field-meta.xml
<CustomField>
    <fullName>X2H_Vaxchora_Gap__c</fullName>
    <label>2H Vaxchora Gap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/classes/SalesPlannerHistoryController.cls
/* ***************************************************************
* Owner/Modify by Name : Prashant Damke
* @description: It used in SalesPlanner History aura component
* @Change:  
* @last modify by:  Prashant Damke
* @last modify date:  9-Jan-2020
* *************************************************************** */
public class SalesPlannerHistoryController {
    /* ***************************************************************
    * @description: This function check the User profile id with the System Admin profile ID
    * @Change:  
    * *************************************************************** */
    @AuraEnabled
    public Static Boolean getIsAdmin()
    {
        //If User profile id equal the System Admin profile ID then it return true else false
        if (String.valueOf(UserInfo.getProfileId()).contains(Label.pvSystemProfileId))
            return true; 
        else
            return false;
    }
    /* ***************************************************************
    * @description: This function return all SP History records those are deleted
    * @Change:  
    * *************************************************************** */
    @AuraEnabled
    public Static List<Sales_Planner_History__c> getSalesPlannerHistory(String accountId)
    {
        //fetche the List of SP History record based on the SOQL
        List<Sales_Planner_History__c> spHistory = [select id,Name, Sales_Planner_Year__c,Account_Sales_Planner_History__c,Vivotif_Committed_Doses__c,
                                               Account_Stage__c,DDD_Outlet_ID__c,Outlet_Name__c,Sales_Planner_Id__c,Account_Owner__c,
                                              H_RAM_Projected_Vaxchora_1__c,X1H_Actual_Vaxchora_Doses__c,X1H_Vaxchora_Gap__c,H_RAM_Projected_Vaxchora_2__c,
                                              X2H_Actual_Vaxchora_Doses__c,X2H_Vaxchora_Gap__c,Pricing_Discount_Programs__c,Contract_Signed_Date__c,Vaxchora_Doses_Commitment__c,
                                              Vaxchora_Ordered_Doses__c,CreatedById,CreatedBy.Name,LastModifiedById,LastModifiedBy.Name from Sales_Planner_History__c 
                                              where Account_Sales_Planner_History__c =:accountId and Is_Deleted__c=true
                                              order by Sales_Planner_Year__c,LastModifiedDate desc];
        return spHistory; 
    }
    /* ***************************************************************
    * @description: This function return object Icon Name
    * @Change:  
    * *************************************************************** */
    @AuraEnabled
    public static String getIconName(String sObjectName){
        //Declare string and List of object
        String u;
        try{
            List<Schema.DescribeTabSetResult> tabSetDesc = Schema.describeTabs();
            List<Schema.DescribeTabResult> tabDesc = new List<Schema.DescribeTabResult>();
            List<Schema.DescribeIconResult> iconDesc = new List<Schema.DescribeIconResult>();
            //add all Tabs info in List
            for(Schema.DescribeTabSetResult tsr : tabSetDesc) { tabDesc.addAll(tsr.getTabs()); }
            //add Icons for object as per the input parameter
            for(Schema.DescribeTabResult tr : tabDesc) {
                //Check the object name
                if( sObjectName == tr.getSobjectName() ) {
                    //check the object is custom or standard based on the Icons get added in the list
                    if( tr.isCustom() == true ) {
                        iconDesc.addAll(tr.getIcons());
                    } else {
                        u = 'standard:' + sObjectName.toLowerCase();
                    }
                }
            }
            //loop through the List of icons
            for (Schema.DescribeIconResult ir : iconDesc) {
                //check the icon contentType = 'image/svg+xml' and return the actual path of the object
                if (ir.getContentType() == 'image/svg+xml'){
                    u = 'custom:' + ir.getUrl().substringBetween('custom/','.svg').substringBefore('_');
                    break;
                }
            }
            if(test.isRunningTest())
                integer i = 1/0; 
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'getIconName', ex.getMessage(), ex.getLineNumber());
        }
        return u;
    }
    /* ***************************************************************
    * @description: This function retrive the deleted SP
    * @Change:  
    * *************************************************************** */
    @AuraEnabled
    public Static void RetriveRecords(List<String> lstRecordIds){
        //fetch the list of SP History based on the list provided in SOQL
        list<Sales_Planner_History__c> spHistoryList = 
            [select id,Sales_Planner_Id__c, Sales_Planner_Year__c, Is_Deleted__c, 
            Unique_SalesPlanner__c, Name, Issues_Objections_Limitations__c, Action_Plan__c,
            Personal_Note__c, Pricing_Discount_Programs__c, Account_Stage__c,Vivotif_Committed_Doses__c,
            X2019_TotalActivities__c, H_RAM_Projected_Vaxchora_2__c, H_RAM_Projected_Vaxchora_1__c,
            Total_F2F_Meetings__c, Vaxchora_Ordered_Doses__c, Vaxchora_Doses_Commitment__c,
            Account_Sales_Planner_History__c, GPO__c, Last_Person_Visit__c, Next_Follow_Date__c, 
             Contract_Signed_Date__c, Retrieved__c,X2H_Vaxchora_Gap__c
            from Sales_Planner_History__c where id IN:lstRecordIds and Is_Deleted__c=true  limit 1];        
        //pass the SP History list to the function
        performRetrivedAction(spHistoryList);
    }
    /* ***************************************************************
    * @description: This function retrive the deleted SP from recycle bin or from SP History object
    * @Change:  
    * *************************************************************** */
    public static void performRetrivedAction(list<Sales_Planner_History__c> spHistoryList){
        try{
            //check the list of SP History not empty
            if(!spHistoryList.isEmpty())
            {
                //loop through SP History record
                for(Integer i=0;i<spHistoryList.size();i++){
                    //set Retrieved__c equal to true 
                    spHistoryList[i].Retrieved__c=true;
                }
                //update existing SP History records
                update spHistoryList;
                
                //fetch the SP record from the recycle bin based on the SOQL
                Sales_Planner__c objSP = [SELECT Id, Name FROM Sales_Planner__C WHERE ID =:spHistoryList[0].Sales_Planner_Id__c ALL ROWS]; 
                try {
                    //undelete the deleted SP from the Recycle bin
                    undelete objSP;
                     if(test.isRunningTest())
                integer i = 1/0; 
                    
                }  catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'performRetrivedAction', ex.getMessage(), ex.getLineNumber());
        }
                //check the SP record
                if (objSP==null){
                    //fetch the SP record from the SH History
                    objSP = retrive_SPH_To_SP(spHistoryList[0]);
                    //create SP 
                    insert objSP;
                }
                //Update Existing WhatID = SPH ID with WhatID = SP ID in Task, Event and notes object
                retriveExistingSPHActivityHistory(objSP.Id, spHistoryList[0].Id);  
                //Update the Case with retrived SP ID
                updateExistingSalesPlannerHistoryCaseWithSP(objSP.Id, spHistoryList[0].Id);
                //delete the SP History record
                delete spHistoryList;         
            }
             if(test.isRunningTest())
                integer i = 1/0; 
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'retrive_SPH_To_SP', ex.getMessage(), ex.getLineNumber());
        }
    }
    /* ***************************************************************
    * @description: This function create SP object  from SP History object
    * @Change:  
    * *************************************************************** */
    public static Sales_Planner__c retrive_SPH_To_SP(Sales_Planner_History__c sph){                
        Sales_Planner__c objSP =new Sales_Planner__c();
        try{
            objSP.Name = sph.Name;
            objSP.Account_Sales_Planner__c = sph.Account_Sales_Planner_History__c;
            objSP.Unique_SalesPlanner__c = sph.Unique_SalesPlanner__c;
            objSP.Sales_Planner_Year__c = sph.Sales_Planner_Year__c;
            objSP.Issues_Objections_Limitations__c = sph.Issues_Objections_Limitations__c;
            objSP.Action_Plan__c = sph.Action_Plan__c;
            objSP.Note__c = sph.Personal_Note__c;
            objSP.Pricing_Discount_Programs__c = sph.Pricing_Discount_Programs__c;
            objSP.Account_Stage__c = sph.Account_Stage__c;
            objSP.X2019_TotalActivities__c = sph.X2019_TotalActivities__c;
            objSP.H_RAM_Projected_Vaxchora_2__c = sph.H_RAM_Projected_Vaxchora_2__c;
            objSP.H_RAM_Projected_Vaxchora_1__c = sph.H_RAM_Projected_Vaxchora_1__c;
            objSP.Total_F2F_Meetings__c = sph.Total_F2F_Meetings__c;
            objSP.Vaxchora_Ordered_Doses__c = sph.Vaxchora_Ordered_Doses__c;
            objSP.Vaxchora_Doses_Commitment__c = sph.Vaxchora_Doses_Commitment__c;
            objSP.Vivotif_Committed_Doses__c = sph.Vivotif_Committed_Doses__c;
            objSP.GPO__c = sph.GPO__c;
            objSP.Last_Person_Visit__c = sph.Last_Person_Visit__c;
            objSP.Contract_Signed_Date__c = sph.Contract_Signed_Date__c;
            objSP.Next_Follow_Date__c = sph.Next_Follow_Date__c;
            if(test.isRunningTest())
                integer i = 1/0; 
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'retrive_SPH_To_SP', ex.getMessage(), ex.getLineNumber());
        }
        return objSP;
    }
    /* ***************************************************************
    * @description: Update existing Task, Event and Notes reference from SPH ID to SP ID
    * @Change:  
    * *************************************************************** */
    public static void retriveExistingSPHActivityHistory(Id idSP, Id idSPH){ 
        try{
            //create Task list object based on the SOQL defined
            List<Task> objTask=[Select ID,Subject, whatid from Task where whatid=:idSPH];

            //to check the List is not empty
            if (!objTask.isEmpty()){
                //create Task list object for bulk update
                List<Task> updTaskList= new List<Task>();
                for(Task tsk : objTask){
                    tsk.whatid=idSP;  
                    //set veriable true for skipping the trigger validation rules
                    tsk.Skip_Validation_For_Trigger__c = true;
                    //check EndDate value if null the assign Activity Datetime
                    if (tsk.EndDate__c==null){
                        tsk.EndDate__c=tsk.ActivityDateTime__c;
                    }
                    //add task record into the list
                    updTaskList.add(tsk);
                } 
                //to check the List is not empty
                if (!updTaskList.isEmpty())
                {
                    //perform update dml operation
                    update updTaskList;
                }
            }
            //create event list object based on the SOQL defined
            List<Event> objEvent=[Select ID, whatid from Event where whatid=:idSPH];

            //to check the List is not empty            
            if (!objEvent.isEmpty()){
                //create Event list object for bulk update

                List<Event> updEventList= new List<Event>();
                for(Event evt : objEvent){
                    evt.whatid=idSP;
                    //check EndDate value if null the assign Activity Datetime
                    if (evt.EndDateTime==null){
                        evt.EndDateTime=evt.StartDateTime;
                    }
                    //add event record into the list
                    updEventList.add(evt);
                }  
                //to check the List is not empty
                if (!updEventList.isEmpty())
                {
                    //perform update dml operation
                    update updEventList;
                }
            }
            //Notes: Create new ContentDocumentLink and delete existing ContentDocumentLink
            List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
            List<ContentDocumentLink> cdlExt = new List<ContentDocumentLink>();
            //get all contentdocumentids so that you can query on contentnote
            for(ContentDocumentLink cdl : [SELECT Id, LinkedEntityId, ContentDocumentId, ShareType 
                                           FROM ContentDocumentLink WHERE LinkedEntityId =:idSPH])
            {
                //clone the ContentDocumentLink record
                ContentDocumentLink cloned = cdl.clone();
                cloned.LinkedEntityId = idSP;
                //add clone record and cdl record in the list
                cdlList.add(cloned);
                cdlExt.add(cdl);
            } 
            //to check the List is not empty
            if (!cdlList.isEmpty())
            {
                //perform insert dml operation
                insert cdlList;
                //perform delete dml operation
                delete cdlExt;
            }
             if(test.isRunningTest())
                integer i = 1/0; 
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'retriveExistingSPHActivityHistory', ex.getMessage(), ex.getLineNumber());
        }
    }
    /* ***************************************************************
    * @description: Update existing Cases reference from SPH ID to SP ID
    * @Change:  
    * *************************************************************** */
    public static void updateExistingSalesPlannerHistoryCaseWithSP(Id idSP, Id idSPH){ 
        try{
            //create event list object based on the SOQL defined 
            List<Case> objCase=[SELECT CaseNumber, AccountId, Subject, Id, Sales_Planner__c, Sales_Planner_History__c FROM Case where Sales_Planner_History__c=:idSPH];
            //to check the List is not empty
            if (!objCase.isEmpty()){
                //create Case list object for bulk update
                List<Case> updCaseList= new List<Case>();
                for(Case c : objCase){
                    //assign SP refernce to SP ID
                    c.Sales_Planner__c=idSP;
                    //assign existing SPH refernce id to null
                    c.Sales_Planner_History__c=null;
                    updCaseList.add(c);
                }   
                //to check the List is not empty
                if (!updCaseList.isEmpty())
                {
                    //perform update dml operation
                    update updCaseList;
                } 
            }
             if(test.isRunningTest())
                integer i = 1/0; 
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('SalesPlannerHistoryController', 'retriveExistingSPHActivityHistory', ex.getMessage(), ex.getLineNumber());
        }
    }
}