Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/Accounthistorycontroller.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: Controller class for AccountHistory component.
* @Change:  
* @last modify by:  Vishal Soni
* @last modify date:  10-Jan-2020
* *************************************************************** */
public class Accounthistorycontroller {
    /* ***************************************************************
    * @description: Fetching data from task and salesplanner object.
    * @Change:
    * *************************************************************** */ 
    @AuraEnabled
 public Static List<TaskWrapper> gettask(String Relatedto)     
 {  List<TaskWrapper> wrapperList = new list<TaskWrapper>();
     try{
        
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:Relatedto ];
        List<Task> t = [select id,Subject,Description,WhoId,Who.Name, WhatId, What.Name, OwnerId,Owner.Name,CreatedBy.Alias, ActivityDate, Type, Status from Task where Status='Completed' AND (accountid =:salesPlanner.Account_Sales_Planner__c) ORDER BY ActivityDate desc];
        //Code to store the value from wrapper class in list.
        for(task tsk:t){
        	wrapperList.add(new TaskWrapper(tsk));    
        }
        String t1= t[0].WhatId;
        String t2 = t[0].OwnerId;
         if(Test.isRunningTest())
             integer i=1/0;
 }
   catch(exception ex){
            ApexDebugLogController.insertLog('Accounthistorycontroller', 'gettask', ex.getMessage(), ex.getLineNumber());
   }
        return wrapperList;
    }
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: Wrapper class to convert activity date in MM/DD/YYYY format.
* @Change:  
* @last modify by:  Vishal Soni
* @last modify date:  8-Jan-2020
* *************************************************************** */
    public class TaskWrapper{
        @AuraEnabled
        public string formattedDate{get;set;}
        @AuraEnabled
        public task tsks{get;set;}
        public TaskWrapper(task tsk){  
            tsks = tsk;
            //if activity date is not null then format is in MM/DD/YYYY.
        	if(Tsk.ActivityDate != Null){
            	formattedDate = string.valueOf(Tsk.ActivityDate.month())+'/'+string.valueOf(Tsk.ActivityDate.day())+'/'+string.valueOf(Tsk.ActivityDate.year());   
            }    
        }
    }
}