Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Trg_Task_Setting__c/Trg_Task_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting for Trg_Task</description>
    <label>Trg_Task_Setting</label>
</CustomObject>

SandBox-2/force-app/main/default/classes/CreateEventWhenTaskCreatedTest.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: Test Class for Shiptodata class.
* @Change:  
* @last modify by:   Archie Bisen
* @last modify date:  10-Jan-2020
* *************************************************************** */
@istest
public class CreateEventWhenTaskCreatedTest {
    
 @istest static void testcreateTaskHelper(){
      //test record for custom setting
        Trg_Task_Setting__c spSetting =  Trg_Task_Setting__c.getOrgDefaults();
        spSetting.Is_Active__c=true;
        insert spSetting;

     //create a record of account
        Account acc = new Account(Name = 'TestAcc');
        insert acc;
        Contact con = new Contact(FirstName= 'TestCont',LastName = 'LName',AccountId = acc.id);
        insert con;
     
        Test.StartTest();
        //Create a record of SalesPlanner
        Sales_Planner__c sp = new Sales_Planner__c(Name = 'MyTestSalesPlanner',Account_Sales_Planner__c=acc.Id,Sales_Planner_Year__c='2020');
        insert sp;
     //craete a new tasks 
	  List<task> tskList = new List<Task>();
     
        Task newTask = new Task(CreateEventWhenTaskCreated__c = true,Subject='Test task',ActivityDate = system.today().addDays(2),
                                whatId = sp.Id,OwnerId=UserInfo.getUserId(), Status='Open',
                                ActivityDateTime__c=datetime.newInstance(2019, 9, 15, 11, 30, 0),TaskSalesplannerDetails__c='Address');
         tskList.add(newTask);
     
     Task newTask2 = new Task(CreateEventWhenTaskCreated__c = true,Subject='Test task2',ActivityDate = system.today().addDays(4),
                                whatId = sp.Id,OwnerId=UserInfo.getUserId(), Status='Open',
                                ActivityDateTime__c=datetime.newInstance(2019, 9, 15, 11, 30, 0),TaskSalesplannerDetails__c='Address');
         tskList.add(newTask2);
     
     insert tskList;
     //perform update operation on a task
     newTask.Subject='testupdate';
     update newtask;
     //perform delete operation on a task
     	delete newTask;
      
     
     
 }}