Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/X2019_TotalActivities__c.field-meta.xml
<CustomField>
    <fullName>X2019_TotalActivities__c</fullName>
    <label>CY Total  Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/classes/Trg_Task_Helper.cls
/* ***************************************************************
* Owner/Modify by Name : Sai G
* @description: Heper class for Trg_Task trigger
* @Change:  
* @last modify by:  Vishal Soni
* @last modify date:  17-Jan-2020
* *************************************************************** */
public class Trg_Task_Helper {
    //After insert method for update account records.
    public static void afterinsert(list<Task> trgNew)
    {
        accountUpdate(trgNew);
    }
     //After insert update for update account records.
    public static void afterUpdate(list<Task> trgNew)
    {
        accountUpdate(trgNew);
    }
     //After Delete update for update account records.
    public static void afterDelete(list<Task> trgOld)
    {
        accountUpdate(trgOld);
    }
    
    //After insert update for update account records.
    public static void accountUpdate(List<Task> trgNew)
    {
        Set<Id> setids=new Set<Id>();                       
        for(Task t : trgNew)
        {    
         if(t.Status=='Completed')
        {  
            setids.add(t.WhatId);    

        }
            
        } 
        //creating list salesplanner object records.
        List<Sales_Planner__c> updateAcc=new List<Sales_Planner__c>();
        //Getting task related to salesplanner object.
        List<Sales_Planner__c> LisSales=[select id,X2019_TotalActivities__c,(select id,status,Type,WhatId from Tasks where status='Completed' ) from Sales_Planner__c   where id In:setids];
        for(Sales_Planner__c a: LisSales)
        {
            
            a.X2019_TotalActivities__c=a.Tasks.size();
            updateAcc.add(a);
        }
        update updateAcc;
    }
    
}