Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <formula>Account_Sales_Planner__r.Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner</label>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Account_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_ID__c</fullName>
    <description>Account Owner ID</description>
    <formula>CASESAFEID(Account_Sales_Planner__r.Owner.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner ID</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Untouched_Days__c.field-meta.xml
<CustomField>
    <fullName>Untouched_Days__c</fullName>
    <formula>Today()-DATEVALUE(LastModifiedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Untouched Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/classes/SPEmailBatchTest.cls
/* ***************************************************************
* Owner/Modify by Name : Prashant Damke
* @description: It used to test SPEmailBatch class 
* @Change:  
* @last modify by:  Prashant Damke
* @last modify date:  10-Jan-2020
* *************************************************************** */
@isTest
public class SPEmailBatchTest
{
    /* ***************************************************************
    * @description: This function used for code coverage 
    * @Change:  
    * *************************************************************** */
    @isTest
    static public void TestMeth()
    {
        //declare variable with hardcoded OwnerID
        String iOwnerID = '005610000020lCoAAI';
        //Dummy Data addition code
        //fetch standard user profile based on the SOQL
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        //create user with standard profile
        User u = new User(
            Alias = 'styu', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId =profileId.id , 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='stauser@gmail.com');
        //insert user record
        insert u;
        //create account object with dummy data        
        Account pAcc = new Account(Name='Parent TestAcc');
        //insert account data
        insert pAcc;
        //create a list of account object
        List<Account> lstAcc = new List<Account>();
        //create a multiple account using below loop
        for (Integer i=1;i<=10;i++){
            Account a = new Account(Name='TestAcc-' + string.valueOf(i), OwnerId = iOwnerID, ParentId = pAcc.Id);
            lstAcc.add(a);
        }
        //use below statement to avoid the Multiple DML execution exception
        system.runAs(u){
            //insert list of accounts
            insert lstAcc;
        }
        //create list of Sales Planner object
        List<Sales_Planner__c> lstSP = new List<Sales_Planner__c>();
        //create salesplanner record using loop
        for (Integer i=1;i<=10;i++){
            //create SalesPlanner record
            Sales_Planner__c sp = new Sales_Planner__c(Name='zensarTest-' + string.valueOf(i) ,Sales_Planner_Year__c='2020',
                                                       Account_Sales_Planner__c=lstAcc[i-1].Id);
            lstSP.add(sp);
        }
        //insert listo f Sales Planner records
        insert lstSP;
         
        //declare the Task List and event list object
        List<Task> lstTask = new List<Task>();
        List<Event> lstEvent = new List<Event>();
        //fetch SalesPlanner record using SOQL 
        List<Sales_Planner__c> splist = [select id,Account_Sales_Planner__c,name,Sales_Planner_Year__c,
                                         Account_Sales_Planner__r.OwnerId,Untouched_Days__c,Account_Owner__c,Account_Owner_ID__c from Sales_Planner__c where Id in: lstSP];
        //loop through the List of Sales Planner
         Date dt;
        for (Integer i=0;i<splist.size();i++){
            //check the i values
            if (i==0 || i==2 || i==4 || i==6 || i==8 || i==10){
                //create task record with dummy values               
                if (dt==null){
                    dt = system.today().addDays(-31);
                }
                else{
                    dt = dt.addDays(-31);
                }
                Task newTask = new Task(CreateEventWhenTaskCreated__c = true,Status='Open',Subject='Test task-' + i,
                                        ActivityDate = dt,whatId = splist[i].Id,OwnerId=iOwnerID, type='In Person',
                                        ActivityDateTime__c=dt,TaskSalesplannerDetails__c='Address');
                //add task records in the list
                lstTask.add(newTask);
            }
            else{
                //declare variable with dynamic value
                DateTime eDate = system.today().addDays(-8*(i+1));
                //add 60 minutes
                eDate = eDate.addMinutes(60);
                //create event records with dummy values
                Event nEvent = new Event(Subject='Test Event -' + i,
                                         StartDateTime = system.today().addDays(-8*(i+1)),  type='In Person',
                                         EndDateTime = eDate,
                                         whatId = splist[i].Id, OwnerId=iOwnerID);
                //add events records in the list
                lstEvent.add(nEvent);
            }            
        }
        //loop through the List of Sales Planner
        for (Integer i=0;i<splist.size();i++){
            //create task record with dummy values
            Task newTask = new Task(CreateEventWhenTaskCreated__c = true,Status='Open',Subject='Test task-' + i,
                                    ActivityDate = system.today().addDays(-75*(i+1)),whatId = splist[i].Id,OwnerId=iOwnerID, type='Email',
                                    ActivityDateTime__c=system.today().addDays(-75*(i+1)),TaskSalesplannerDetails__c='Address');
            //add task records in the list
            lstTask.add(newTask);
        }
        //insert task  list 
        insert lstTask;      
        //insert event list
        insert lstEvent;
        
        //**********************************
        //declare the BatchableContext 
        Database.BatchableContext BC;
        //start the code coverage execution
        Test.startTest();
        //create the SPEmailBatch object
        SPEmailBatch obj = new SPEmailBatch();
        //execute the SPEmailBatch class method
        DataBase.executeBatch(obj); 
        //stop the code coverage execution
        Test.stopTest();
    }
}