Production/force-app/main/default/objects/Daily_Sales_Data__c/Daily_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Vaxchora Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vaxchora Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Daily_Sales_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_ID__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_ID__c</fullName>
    <label>ShipTo ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/ShipTo_Information__c/ShipTo_Information__c.object-meta.xml
<CustomObject>
    <label>ShipTo Information</label>
    <nameField>
        <label>ShipTo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShipTo Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShipTo Informations</relationshipLabel>
    <relationshipName>ShipTo_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/DeleteDailySaleWhenShipToDeleteC.cls
/* ***************************************************************
* Owner/Modify by Name : Vivek A
* @description: Handler class used  for DeleteDailySaleWhenShipToDelete trigger
* @Change:  
* @last modify by:  Vivek A
* @last modify date:  08-Jan-2020
* *************************************************************** */
public class DeleteDailySaleWhenShipToDeleteC 
{
    /* ***************************************************************
* @description: calling function BeforeDeleting the ShipToInformation record 
* @Change:
* *************************************************************** */
    public static void getDailyRecToDel(ShipTo_Information__c s)
    {
         list<Daily_Sales_Data__c> lstDailyRecDirect = new  list<Daily_Sales_Data__c>();
       
           
            // get dailySales records related to ShipToInformation record
            lstDailyRecDirect =[SELECT Id, Name, Account__c,ShipTo_ID__c,Quantity__c, DDD_Outlet_ID__c 
                                FROM Daily_Sales_Data__c where 
                                ShipTo_ID__c=:s.Ship_To__c And Account__c=:s.Account__c and ShipTo_Type__c='Direct'];
             try{
            //delete all records in the list 
            delete lstDailyRecDirect;
            //to get exception
            if(test.isRunningTest())
                integer i = 1/0;
            
        }catch(Exception ex){
            ApexDebugLogController.insertLog('DeleteDailySaleWhenShipToDeleteC', 'getDailyRecToDel', ex.getMessage(), ex.getLineNumber());
        }
    }  
}