SandBox-2/force-app/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual Product Loyal</fullName>
            </value>
            <value>
                <fullName>Vaxchora Supporter</fullName>
            </value>
            <value>
                <fullName>Vivotif Supporter</fullName>
            </value>
            <value>
                <fullName>Travel Vaccinator</fullName>
            </value>
            <value>
                <fullName>PaxVax Naïve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>IMS City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Case/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Planner</label>
    <referenceTo>Sales_Planner__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case/fields/Vaxchora_2_8_Reminder_Cling__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_2_8_Reminder_Cling__c</fullName>
    <description>PAX-US-0316</description>
    <inlineHelpText>PAX-US-0316</inlineHelpText>
    <label>Vaxchora “2-8” Reminder Cling</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case/fields/Vaxchora_2_8C_FAQ_Flashcard__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_2_8C_FAQ_Flashcard__c</fullName>
    <description>PAX-US-0320</description>
    <inlineHelpText>PAX-US-0320</inlineHelpText>
    <label>Vaxchora “2-8C” FAQ Flashcard</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case/fields/Vaxchora_Reconstitution_Cling__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_Reconstitution_Cling__c</fullName>
    <description>PAX-US-0317</description>
    <inlineHelpText>PAX-US-0317</inlineHelpText>
    <label>Vaxchora Reconstitution Cling</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case/fields/Vivotif_Pochette_Pouch_with_PIs__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Pochette_Pouch_with_PIs__c</fullName>
    <description>PAX-US-0034 Vivotif Pochette/Pouch with PIs</description>
    <inlineHelpText>PAX-US-0034 Vivotif Pochette/Pouch with PIs</inlineHelpText>
    <label>Vivotif Pochette/Pouch with PIs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/Case_Trigger_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting for deactivation of case trigger</description>
    <label>Case Trigger setting</label>
</CustomObject>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vax_Flashcard_Reconstitution_Remind_Erro__c.field-meta.xml
<CustomField>
    <fullName>Vax_Flashcard_Reconstitution_Remind_Erro__c</fullName>
    <label>Vax_Flashcard,Reconstitution,Remind Erro</label>
    <type>TextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vaxchora_2_8_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_2_8_Reminder__c</fullName>
    <description>Vaxchora “2-8” Reminder</description>
    <label>Vaxchora “2-8” Reminder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vaxchora_2_8C_FAQ__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_2_8C_FAQ__c</fullName>
    <description>Vaxchora “2-8C” FAQ</description>
    <label>Vaxchora “2-8C” FAQ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vaxchora_Reconstitution__c.field-meta.xml
<CustomField>
    <fullName>Vaxchora_Reconstitution__c</fullName>
    <description>Vaxchora Reconstitution</description>
    <label>Vaxchora Reconstitution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vivotif_Pochette_Pouch__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Pochette_Pouch__c</fullName>
    <description>Vivotif Pochette/Pouch</description>
    <label>Vivotif Pochette/Pouch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Case_Trigger_Setting__c/fields/Vivotif_Pochette_Pouch_with_PIs_c_Error__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Pochette_Pouch_with_PIs_c_Error__c</fullName>
    <label>Vivotif_Pochette_Pouch_with_PIs__c Error</label>
    <type>TextArea</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Account_Sales_Planner__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IMS City</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/classes/ValidateCaseFieldTest.cls
/* ***************************************************************
* Owner/Modify by Name : Vivek A
* @description: ValidateCaseFieldTest is used to provide test data for ValidateCaseField for code coverage.
* @Change:  
* @last modify by:  Vivek A
* @last modify date:  14-Jan-2020
* *************************************************************** */

@istest
public class ValidateCaseFieldTest {
    @istest
    /* ***************************************************************
* @description: calling function to pass test data to ValidateCaseField class for code coverage
* @Change:
* *************************************************************** */
    public static void testMeth1()
    {
        //test record for custom setting
        Case_Trigger_Setting__c spSetting =  Case_Trigger_Setting__c.getOrgDefaults();
        spSetting.Is_Active__c=true;
        spSetting.Vaxchora_2_8_Reminder__c='200';
        spSetting.Vaxchora_2_8C_FAQ__c='200';
        spSetting.Vaxchora_Reconstitution__c='200';
        spSetting.Vivotif_Pochette_Pouch__c='200';
        spSetting.Vivotif_Pochette_Pouch_with_PIs_c_Error__c='hello';
        spSetting.Vax_Flashcard_Reconstitution_Remind_Erro__c='hi';
        insert spSetting;
        //get user
        User u = [Select id, ProfileId from User where Alias= 'jbjer' LIMIT 1];
        System.runAs ( u ){
            //test data for account record
            Account a = new Account(Name='TestViv123');
            //insert Account
            insert a;
            //test data for salesplanner record related to account inserted above
            Sales_Planner__c s = new Sales_Planner__c(Name='Test123',Sales_Planner_Year__c='2020',
                                                      Account_Sales_Planner__c=a.id,
                                                      Account_Stage__c='Vivotif Supporter');
            //insert salesplanner
            insert s;
            //test data for case record related to salesplanner created above
            case c = new case(Sales_Planner__c=s.id,
                              OwnerId=u.id,Vivotif_Pochette_Pouch_with_PIs__c=20,
                              Reason='Marketing Materials Request',
                              Status='New',
                              Facility_Name__c='test',
                              Shipping_Address__c ='test',
                              City__c='test', State__c='test', Zip_Code__c='iop');
            //insert case
            insert c;
            //provide Vivotif_Pochette_Pouch_with_PIs__c so that it exceeds limit
            c.Vivotif_Pochette_Pouch_with_PIs__c=208;
            //try to update Vivotif_Pochette_Pouch_with_PIs__c field
            try{
                update c;    
            }catch(exception ex){
                ApexDebugLogController.insertLog('ValidateCaseFieldTest', 'testMeth1', ex.getMessage(), ex.getLineNumber());
            }
            //test data for case related to salesplanner inserted above
            case c1 = new case(Sales_Planner__c=s.id,
                               OwnerId=u.id,Vivotif_Pochette_Pouch_with_PIs__c=200,
                               Reason='Marketing Materials Request',
                               Status='New',
                               Facility_Name__c='test1',
                               Shipping_Address__c ='test',
                               City__c='test', State__c='test1', Zip_Code__c='iop');
            //try to insert test case 
            try{
                insert c1;
            }
            catch(exception ex)
            {
                ApexDebugLogController.insertLog('ValidateCaseFieldTest', 'testMeth1', ex.getMessage(), ex.getLineNumber());
            }
            //test data for case related to salesplanner inserted above
            case c2 = new case(Sales_Planner__c=s.id,
                               OwnerId=u.id,Vaxchora_2_8C_FAQ_Flashcard__c=200,
                               Vaxchora_2_8_Reminder_Cling__c=200,
                               Vaxchora_Reconstitution_Cling__c=200,
                               Reason='Marketing Materials Request',
                               Status='New',
                               Facility_Name__c='test1',
                               Shipping_Address__c ='test',
                               City__c='test', State__c='test1', Zip_Code__c='iop');
            //try to insert case c2
            try{
                insert c2;
            }
            catch(exception ex)
            {
                ApexDebugLogController.insertLog('ValidateCaseFieldTest', 'testMeth1', ex.getMessage(), ex.getLineNumber());
            }
            //assign values so that it exceeds the limit
            c2.Vaxchora_2_8C_FAQ_Flashcard__c=201;
            c2.Vaxchora_2_8_Reminder_Cling__c=201;
            c2.Vaxchora_Reconstitution_Cling__c=201;
            //try updating c2.
            try{
                update c2;
            }
            catch(exception ex)
            {
                ApexDebugLogController.insertLog('ValidateCaseFieldTest', 'testMeth1', ex.getMessage(), ex.getLineNumber());
            }
            //test data for case record
            case c3 = new case(Sales_Planner__c=s.id,
                               OwnerId=u.id,Vaxchora_2_8C_FAQ_Flashcard__c=201,
                               Vaxchora_2_8_Reminder_Cling__c=201,
                               Vaxchora_Reconstitution_Cling__c=201,
                               Reason='Marketing Materials Request',
                               Status='New',
                               Facility_Name__c='test1',
                               Shipping_Address__c ='test',
                               City__c='test', State__c='test1', Zip_Code__c='iop');
            //try to insert c3
            try{
                insert c3;
            }
            catch(exception ex)
            {
                ApexDebugLogController.insertLog('ValidateCaseFieldTest', 'testMeth1', ex.getMessage(), ex.getLineNumber());
            }
        }
    }
}