SandBox-2/force-app/main/default/objects/Account/fields/Account_Stage__c.field-meta.xml
<CustomField>
    <fullName>Account_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual Product Loyal</fullName>
            </value>
            <value>
                <fullName>Vaxchora Supporter</fullName>
            </value>
            <value>
                <fullName>Vivotif Supporter</fullName>
            </value>
            <value>
                <fullName>Travel Vaccinator</fullName>
            </value>
            <value>
                <fullName>PaxVax Naïve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <label>Monthly Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/classes/HorizontalMonthlyChartsDisplayTest.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: It used to test HorizontalMonthlyChartsDisplay class 
* @Change:  
* @last modify by:  Prashant Damke
* @last modify date:  10-Jan-2020
* *************************************************************** */
@isTest
public class HorizontalMonthlyChartsDisplayTest {
    /* ***************************************************************
    * @description: This function used for code coverage 
    * @Change:  
    * *************************************************************** */
    @isTest
    public static void testHorizontal()
    {
        //create a Account object with dummy data
        Account a = new Account(Name='TestViv123');
        //insert account record
        insert a;
        //create SP object with dummy data
        Sales_Planner__c s = new Sales_Planner__c(Name='Test123',Sales_Planner_Year__c='2020',
                                                  Account_Sales_Planner__c=a.id,
                                                  Account_Stage__c='Vivotif Supporter');
        //insert SP record
        insert s;
        //create Sales Data object with dummy data
        Sales_Data__c sd = new Sales_Data__c();
        sd.Name='testsd';
        sd.Account__c=a.id;
        //insert Sales Data
        insert sd;
        //check the assertion
        system.assertEquals(sd.Name, 'testsd');
        //start the code coverage execution
        test.startTest();
        //execute below methods with dummy data
        HorizontalMonthlychartsDisplay.getMonthlyData(s.id,'Vivotif');
        HorizontalMonthlychartsDisplay.getMonthlyDataReverse(s.id,'Vivotif');
        //stop the code coverage execution
        test.stopTest(); 
    }        
}