SandBox-2/force-app/main/default/objects/Account/fields/Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price__c</fullName>
    <label>Contract Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Production/force-app/main/default/objects/Account/fields/Current_Vivotif_Contract__c.field-meta.xml
<CustomField>
    <fullName>Current_Vivotif_Contract__c</fullName>
    <label>Current Vivotif Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MHA</fullName>
            </value>
            <value>
                <fullName>Premier/INNOVATIX</fullName>
            </value>
            <value>
                <fullName>MMS/MMCAP</fullName>
            </value>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Armada</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>PDM</fullName>
            </value>
            <value>
                <fullName>NPC</fullName>
            </value>
            <value>
                <fullName>PediaFed</fullName>
            </value>
            <value>
                <fullName>USPPG</fullName>
            </value>
            <value>
                <fullName>Physician&#39;s Alliance</fullName>
            </value>
            <value>
                <fullName>College/University Umbrella</fullName>
            </value>
            <value>
                <fullName>Group Travel Umbrella</fullName>
            </value>
            <value>
                <fullName>City/County Umbrella</fullName>
            </value>
            <value>
                <fullName>Kaiser</fullName>
            </value>
            <value>
                <fullName>State of TX</fullName>
            </value>
            <value>
                <fullName>State of CA</fullName>
            </value>
            <value>
                <fullName>FSS/Govt/DOD</fullName>
            </value>
            <value>
                <fullName>Passport Health</fullName>
            </value>
            <value>
                <fullName>TravelCare WorldWide</fullName>
            </value>
            <value>
                <fullName>Travel Clinics of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For toggling Apex functionality</description>
    <label>TriggerSettings</label>
</CustomObject>

Production/force-app/main/default/objects/TriggerSettings__c/fields/TriggersEnabled__c.field-meta.xml
<CustomField>
    <fullName>TriggersEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For toggling all Apex triggers</description>
    <label>TriggersEnabled</label>
    <type>Checkbox</type>
</CustomField>

SandBox-2/force-app/main/default/objects/TriggerSettings__c/fields/updateContractAmount__c.field-meta.xml
<CustomField>
    <fullName>updateContractAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Populates Account.Contract Amount from Vivotif Contract object</description>
    <label>updateContractAmount</label>
    <type>Checkbox</type>
</CustomField>

Production/force-app/main/default/objects/Vivotif_Contract__c/Vivotif_Contract__c.object-meta.xml
<CustomObject>
    <description>For updating Vivotif contracts</description>
    <label>Vivotif Contract</label>
    <nameField>
        <displayFormat>VC-{00000000}</displayFormat>
        <label>Vivotif Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vivotif Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Vivotif_Contract__c/fields/Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price__c</fullName>
    <description>Captures contract price</description>
    <label>Contract Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Vivotif_Contract__c/fields/Vivotif_Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Contract_Name__c</fullName>
    <description>Captures contract name</description>
    <externalId>true</externalId>
    <label>Vivotif Contract Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Production/force-app/main/default/classes/AccountHelper_Test.cls
@isTest
public class AccountHelper_Test {
    public static testMethod void updateContractAmounts(){
        TriggerSettings__c settings = new TriggerSettings__c(TriggersEnabled__c = true,
                                                            updateContractAmount__c = true);
        insert settings;
        
        Vivotif_Contract__c contract1 = new Vivotif_Contract__c(Vivotif_Contract_Name__c = 'Test Contract 1',
                                                               Contract_Price__c = 100);
        insert contract1;
        
        
        Vivotif_Contract__c contract2 = new Vivotif_Contract__c(Vivotif_Contract_Name__c = 'Test Contract 2',
                                                               Contract_Price__c = 200);
        insert contract2;
        
        Account a = new Account(Name = 'Test Account',
                               Current_Vivotif_Contract__c = 'Test Contract 1',
                               Contract_Price__c = 0);
        test.startTest();
        //test insert
        insert a;
        a = [select Id, Contract_Price__c from Account where Id =: a.Id];
        system.debug('### a.Contract_Price__c: ' + a.Contract_Price__c);
        system.assert(a.Contract_Price__c == 100);
        
        //test update
        a.Current_Vivotif_Contract__c = 'Test Contract 2';
        update a;
        a = [select Id, Contract_Price__c from Account where Id =: a.Id];
        system.debug('### a.Contract_Price__c: ' + a.Contract_Price__c);
        system.assert(a.Contract_Price__c == 200);
        
        //test no Account Contract specified
        a.Current_Vivotif_Contract__c = null;
        update a;
        a = [select Id, Contract_Price__c from Account where Id =: a.Id];
        system.debug('### a.Contract_Price__c: ' + a.Contract_Price__c);
        system.assert(a.Contract_Price__c == null);
        
        //test Contract record doesn't exist
        a.Current_Vivotif_Contract__c = 'Does Not Exist';
        update a;
        a = [select Id, Contract_Price__c from Account where Id =: a.Id];
        system.debug('### a.Contract_Price__c: ' + a.Contract_Price__c);
        system.assert(a.Contract_Price__c == null);
        test.stopTest();
    }
}