SandBox-2/force-app/main/default/objects/Account/fields/Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price__c</fullName>
    <label>Contract Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Production/force-app/main/default/objects/Account/fields/Current_Vivotif_Contract__c.field-meta.xml
<CustomField>
    <fullName>Current_Vivotif_Contract__c</fullName>
    <label>Current Vivotif Contract</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MHA</fullName>
            </value>
            <value>
                <fullName>Premier/INNOVATIX</fullName>
            </value>
            <value>
                <fullName>MMS/MMCAP</fullName>
            </value>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Armada</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>PDM</fullName>
            </value>
            <value>
                <fullName>NPC</fullName>
            </value>
            <value>
                <fullName>PediaFed</fullName>
            </value>
            <value>
                <fullName>USPPG</fullName>
            </value>
            <value>
                <fullName>Physician&#39;s Alliance</fullName>
            </value>
            <value>
                <fullName>College/University Umbrella</fullName>
            </value>
            <value>
                <fullName>Group Travel Umbrella</fullName>
            </value>
            <value>
                <fullName>City/County Umbrella</fullName>
            </value>
            <value>
                <fullName>Kaiser</fullName>
            </value>
            <value>
                <fullName>State of TX</fullName>
            </value>
            <value>
                <fullName>State of CA</fullName>
            </value>
            <value>
                <fullName>FSS/Govt/DOD</fullName>
            </value>
            <value>
                <fullName>Passport Health</fullName>
            </value>
            <value>
                <fullName>TravelCare WorldWide</fullName>
            </value>
            <value>
                <fullName>Travel Clinics of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/Vivotif_Contract__c/Vivotif_Contract__c.object-meta.xml
<CustomObject>
    <description>For updating Vivotif contracts</description>
    <label>Vivotif Contract</label>
    <nameField>
        <displayFormat>VC-{00000000}</displayFormat>
        <label>Vivotif Contract</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vivotif Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Vivotif_Contract__c/fields/Contract_Price__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price__c</fullName>
    <description>Captures contract price</description>
    <label>Contract Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Vivotif_Contract__c/fields/Vivotif_Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Vivotif_Contract_Name__c</fullName>
    <description>Captures contract name</description>
    <externalId>true</externalId>
    <label>Vivotif Contract Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Production/force-app/main/default/classes/AccountHelper.cls
public class AccountHelper {
    public static void updateContractAmount(List<Account> accounts){
        Map<String, Decimal> contractNameAmount = new Map<String, Decimal>();
        for(Vivotif_Contract__c contract : [select Vivotif_Contract_Name__c, Contract_Price__c from Vivotif_Contract__c]){
            contractNameAmount.put(contract.Vivotif_Contract_Name__c, contract.Contract_Price__c);
        }
        system.debug('### AccountHelper.updateContractAmount() found [' + contractNameAmount.size() + '] values');
        for (Account a : accounts){
            if(a.Current_Vivotif_Contract__c <> null){
                if(contractNameAmount.containsKey(a.Current_Vivotif_Contract__c)){
                    a.Contract_Price__c = contractNameAmount.get(a.Current_Vivotif_Contract__c);
                }
                else{
                    system.debug('### AccountHelper.updateContractAmount - No matching VC record found for contract: ' + a.Current_Vivotif_Contract__c);
                    a.Contract_Price__c = null;
                }
            }
            else{
                system.debug('### AccountHelper.updateContractAmount - No contract value supplied');
                a.Contract_Price__c = null;
            }
        }
    }
}