SandBox-2/force-app/main/default/objects/Account/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <externalId>true</externalId>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Account_Sales_Planner__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account_ID</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <formula>Account_Sales_Planner__r.DDD_Outlet_ID__c</formula>
    <label>DDD Outlet ID</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <formula>HYPERLINK( Account_Sales_Planner__r.Parent.Id , Account_Sales_Planner__r.Parent.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Account</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/AccHierarchyApex.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: AccHierarchyApex class is used to fetch the parent and child accounts to display in lightning component. 
* @Change:  
* @last modify by:  Vivek A
* @last modify date:  10-Jan-2020
* *************************************************************** */
public class AccHierarchyApex {
    /* ***************************************************************
	* @description: calling function to get acccount details/Saleplanner record details.
	* @Change:
	* *************************************************************** */
    @AuraEnabled
    public static string getAccountId(string spId){
        //if spId parameter is not null and if is starts with 'a19' and not with '001' ,it return the corresponding accounId.

        if(spId != null && !spId.startsWithIgnoreCase('001') && spId.startsWithIgnoreCase('a19')){
            return [select id,name,Account_Sales_Planner__c,Parent_Account__c,Account_ID__c from Sales_Planner__c where id =:spId LIMIT 1].Account_ID__c;  
        }
       //else returns the same salesplanner Id
        else
            return spId;
    }
    
     /* ***************************************************************
	* @description: calling function to get details of all hierarchy of acccount.
	* @Change:
	* *************************************************************** */
    @AuraEnabled
    public static List<Account> findHierarchyData(string recId){
        List<Account> accList = new List<Account>();
        try{
         //if recId parameter is not null and if is starts with 'a19' and not with '001', recId is assigned with AccountId.
        if(recId != null && !recId.startsWithIgnoreCase('001') && recId.startsWithIgnoreCase('a19')){
            recId = [select id,name,Account_Sales_Planner__c,Parent_Account__c,Account_ID__c from Sales_Planner__c where id =:recId LIMIT 1].Account_ID__c;  
            
        }
        
        string queryString = 'select id,name,Owner.Name,parentId,DDD_Outlet_ID__c,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry from Account';
        
        //Section to get all child account details from ultimate parent
        List<String> currentParent  = new List<String>{};
            Integer level               = 0;
        Boolean endOfStructure      = false;
        //method to find ultimate parent of account
        string topMostparent = GetUltimateParentId(recId);
        currentParent.add(topMostparent);
        //Loop though all children
        string finalQueryString = '';
        List<Account>  queryOutput = new List<Account> ();
        while ( !endOfStructure ){  
            if( level == 0 ){
                finalQueryString = queryString + ' where id IN : CurrentParent ORDER BY ParentId ';
            } 
            else {
                finalQueryString = queryString + ' where ParentID IN : CurrentParent ORDER BY ParentId ';
            }
            if(finalQueryString != null && finalQueryString !=''){
                try{
                    if(Limits.getLimitQueries()-Limits.getQueries()>0){
                        queryOutput = database.query(finalQueryString);
                    }else{
                        endOfStructure = true;
                    }
                }catch(exception ex){ 
                    endOfStructure = true;
                }
            }
            if( queryOutput.size() == 0 ){
                endOfStructure = true;
            }
            else{
                currentParent.clear();
                //iterating through query output
                for ( Integer i = 0 ; i < queryOutput.size(); i++ ){
                    currentParent.add(queryOutput[i].Id);
                    accList.add(queryOutput[i]);
                }
            }
            level++;
            if(test.isRunningTest())
                integer i=1/0;
        }
        }catch(Exception ex){
            ApexDebugLogController.insertLog('DeleteDailySaleWhenShipToDeleteC', 'getDailyRecToDel', ex.getMessage(), ex.getLineNumber());
        }
        return accList;
    }
    
    // Find the top most element in Heirarchy  
    public static String GetUltimateParentId( string recId ){
        try{
        Boolean top = false;
        while ( !top ) {
            string queryString = 'select id,name, ParentId from Account where Id =:recId LIMIT 1';
            Account acc = database.query(queryString);
            if ( acc.parentId != null ) {
                recId = acc.parentId;
            }else {
                top = true;
            }
            if(test.isRunningTest())
                integer i=1/0;
        }
        }catch(Exception ex){
            ApexDebugLogController.insertLog('DeleteDailySaleWhenShipToDeleteC', 'getDailyRecToDel', ex.getMessage(), ex.getLineNumber());
        }
        return recId ;
    }
}