SandBox-2/force-app/main/default/objects/Account/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <externalId>true</externalId>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Account/fields/ShipTo_ID__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_ID__c</fullName>
    <label>ShipTo ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/Daily_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Vaxchora Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vaxchora Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Daily_Sales_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Invoice_Line__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line__c</fullName>
    <label>Invoice Line</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Item_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Category__c</fullName>
    <label>Item Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Daily_Sales_Data__c/fields/NDC__c.field-meta.xml
<CustomField>
    <fullName>NDC__c</fullName>
    <label>NDC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Daily_Sales_Data__c/fields/Reason_for_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Transaction__c</fullName>
    <label>Reason for Transaction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_Date__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Date__c</fullName>
    <label>ShipTo Date</label>
    <type>Date</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_ID__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_ID__c</fullName>
    <label>ShipTo ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/ShipTo_Information__c/ShipTo_Information__c.object-meta.xml
<CustomObject>
    <label>ShipTo Information</label>
    <nameField>
        <label>ShipTo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShipTo Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShipTo Informations</relationshipLabel>
    <relationshipName>ShipTo_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/ShipTo_Setting__c/ShipTo_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is created for DeleteDailySaleWhenShipToDelete trigger.
This setting affect the dailysales records deletion when shipto id gets deleted.</description>
    <label>ShipToSetting</label>
</CustomObject>

SandBox-2/force-app/main/default/objects/ShipTo_Setting__c/fields/IsActive_trigger__c.field-meta.xml
<CustomField>
    <fullName>IsActive_trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To deactivate the shipto information trigger</description>
    <label>IsActive_trigger</label>
    <type>Checkbox</type>
</CustomField>

Production/force-app/main/default/classes/DeleteDailySaleWhenShipToDeleteCTest.cls
/* ***************************************************************
* Owner/Modify by Name : Vivek A
* @description: Test Class to provide test data for DeleteDailySaleWhenShipToDeleteC class.
* @Change:  
* @last modify by:  Vivek A
* @last modify date:  09-Jan-2020
* *************************************************************** */
@istest
public class DeleteDailySaleWhenShipToDeleteCTest 
{
    
    /* ***************************************************************
* @description: Method which provides test data for the DeleteDailySaleWhenShipToDeleteC class 
* @Change:
* *************************************************************** */
    @istest
    public static void testMeth1()
    {
         //test record for custom setting
        ShipTo_Setting__c spSetting =  ShipTo_Setting__c.getOrgDefaults();
        spSetting.IsActive_trigger__c=true;
        insert spSetting;
        //to insert test data for Account record
        Account a = new Account();
        a.Name='Test';
        a.DDD_Outlet_ID__c='12345678';
        a.ShipTo_ID__c='1234567890';
        insert a;
        //to insert test data for ShipTo Information record related to Account inserted above
        ShipTo_Information__c sToinfo= new ShipTo_Information__c();
        sToinfo.Name='shiptest';
        sToinfo.Ship_To__c=a.ShipTo_ID__c;
        sToinfo.Account__c=a.Id;
        sToinfo.DDD_Outlet_ID__c=a.DDD_Outlet_ID__c;
        sToinfo.ShipTo_Type__c='Direct';
       
            insert sToinfo;    
        
        //insert test data for Daily sales records related to above inserted shipTo Id
        Daily_Sales_Data__c DSInfo = new Daily_Sales_Data__c();
        DSInfo.Account__c= a.Id;
        DSInfo.ShipTo_ID__c= a.ShipTo_ID__c;
        DSInfo.ShipTo_Date__c= Date.today();
        DSInfo.Quantity__c= 30;
        DSInfo.ShipTo_Type__c='Direct';                               
        DSInfo.Invoice__c= '131624268';
        DSInfo.Invoice_Line__c='1';
        DSInfo.Reason_for_Transaction__c= 'Not assigned';
        DSInfo.NDC__c= '70460-0001-01';
        DSInfo.Item_Category__c='Standard Item';
        DSInfo.Material_Description__c='Vaxchora pwd 1/EA';
        insert DSInfo;
        
        Daily_Sales_Data__c DSInfo1 = new Daily_Sales_Data__c();
        DSInfo1.Account__c= a.Id;
        DSInfo1.ShipTo_ID__c= a.ShipTo_ID__c;
        DSInfo1.ShipTo_Date__c= Date.today();
        DSInfo1.Quantity__c= 20;
        DSInfo1.ShipTo_Type__c='Direct';                               
        DSInfo1.Invoice__c= '131624268';
        DSInfo1.Invoice_Line__c='1';
        DSInfo1.Reason_for_Transaction__c= 'Not assigned';
        DSInfo1.NDC__c= '70460-0001-01';
        DSInfo1.Item_Category__c='Standard Item';
        DSInfo1.Material_Description__c='Vaxchora pwd 1/EA';
        insert DSInfo1;
        
        Daily_Sales_Data__c DSInfo2 = new Daily_Sales_Data__c();
        DSInfo2.Account__c= a.Id;
        DSInfo2.ShipTo_ID__c= '1222';
        DSInfo2.ShipTo_Date__c= Date.today();
        DSInfo2.Quantity__c= 200;
        DSInfo2.ShipTo_Type__c='Direct';                               
        DSInfo2.Invoice__c= '131624268';
        DSInfo2.Invoice_Line__c='1';
        DSInfo2.Reason_for_Transaction__c= 'Not assigned';
        DSInfo2.NDC__c= '70460-0001-01';
        DSInfo2.Item_Category__c='Standard Item';
        DSInfo2.Material_Description__c='Vaxchora pwd 1/EA';
        insert DSInfo2;
        
        //delete shipTo information record, this triggers DeleteDailySaleWhenShipToDelete trigger which inturn calls DeleteDailySaleWhenShipToDeleteC class.
        delete sToinfo;
        
        
    }
}