SandBox-2/force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <label>Monthly Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Doses_Month_0__c.field-meta.xml
<CustomField>
    <fullName>Doses_Month_0__c</fullName>
    <label>Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/QuarterlyChartsDisplay.cls
public class QuarterlyChartsDisplay {
    
    @AuraEnabled
    /* public Static List<AggregateResult> getQuarterly(String SalesPlannerID,String productName,String year)
{
Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:SalesPlannerID ];
List<AggregateResult> saledata;
if (year == 'LAST YEAR')
saledata = [SELECT CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name=:productName and Date__c =last_year GROUP BY CALENDAR_QUARTER(Date__c) ];
else 
saledata = [SELECT CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name=:productName and Date__c =this_year GROUP BY CALENDAR_QUARTER(Date__c) ];    
//List<Sales_Data__c> saledata = [SELECT id FROM Sales_Data__c where Account__c =: salesPlanner.Account_Sales_Planner__c and Date__c = LAST_YEAR];
System.debug('saledata ::: '+saledata);
return saledata;

//CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c)
}*/
    
    
    public Static Map<string,List<AggregateResult>> getVaxQuarterly(String SalesPlannerID,String productName)
    { 
        system.debug('::::SalesPlannerID'+SalesPlannerID);
        system.debug('::::productName' +productName); 
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:SalesPlannerID ];
        List<AggregateResult> saldata;
        List<AggregateResult> saldata2; 
        List<String> prdList = productName.split(',');
        system.debug(':::salesPlanner.Account_Sales_Planner__c'+salesPlanner.Account_Sales_Planner__c);
        Map<string,List<AggregateResult>> prodQuarResult = new Map<string,List<AggregateResult>>();
        saldata = [SELECT CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =last_year GROUP BY CALENDAR_QUARTER(Date__c) ];
        prodQuarResult.put('Lastyear', saldata);
        saldata2 = [SELECT CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =this_year GROUP BY CALENDAR_QUARTER(Date__c) ];    
        //List<Sales_Data__c> saledata = [SELECT id FROM Sales_Data__c where Account__c =: salesPlanner.Account_Sales_Planner__c and Date__c = LAST_YEAR];
        System.debug('saledata ::: '+saldata);
        prodQuarResult.put('Thisyear', saldata2);
        //saldata.addAll(saldata2);
        return prodQuarResult;

        //CALENDAR_QUARTER(Date__c), SUM(Doses_Month_0__c)
    }
    
    
    
    
    
}