SandBox-2/force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <label>Monthly Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Doses_Month_0__c.field-meta.xml
<CustomField>
    <fullName>Doses_Month_0__c</fullName>
    <label>Doses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/HorizontalMonthlychartsDisplay.cls
/* ***************************************************************
* Owner/Modify by Name : Prashant Damke
* @description: Controller class for HorizontalCharts lightning Component.
* @Change:  
* @last modify by:  Vishal Soni
* @last modify date:  13-Jan-2020
* *************************************************************** */
public class HorizontalMonthlychartsDisplay {
     /* ***************************************************************
    * @description: Method to get monthly data from Sales data object.
    * @Change:  
    * *************************************************************** */
  @AuraEnabled    
    public Static Map<string,List<AggregateResult>> getMonthlyData(String SalesPlannerID,String productName)
    {  //create query result MAP : Key = String and Value = list of aggregate results.
        Map<string,List<AggregateResult>> prodQuarResult = new Map<string,List<AggregateResult>>();
        try{
        //Fetch Account and Salesplanner Id from the salesplanner.
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:SalesPlannerID ];
        List<AggregateResult> saldata;
        List<AggregateResult> saldata2; 
        List<String> prdList = productName.split(',');

        prodQuarResult = new Map<string,List<AggregateResult>>();
             //get sales data records for last year
        saldata = [SELECT CALENDAR_MONTH(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =last_year GROUP BY CALENDAR_MONTH(Date__c) order by CALENDAR_MONTH(Date__c)];
        prodQuarResult.put('Lastyear', saldata);
             //get sales data records for this year
        saldata2 = [SELECT CALENDAR_MONTH(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =this_year GROUP BY CALENDAR_MONTH(Date__c) order by CALENDAR_MONTH(Date__c)];    


        prodQuarResult.put('Thisyear', saldata2);
            if(Test.isRunningTest())
                integer i=1/0;

        } 
        catch(exception ex){
            ApexDebugLogController.insertLog('HorizontalMonthlychartsDisplay', 'getMonthlyData', ex.getMessage(), ex.getLineNumber());
        }
        
        return prodQuarResult;
     


    }
   /* ***************************************************************
    * @description: Method to get monthly data from Sales data object by month in descending order.
    * @Change:  
    * *************************************************************** */
    @AuraEnabled    
    public Static Map<string,List<AggregateResult>> getMonthlyDataReverse(String SalesPlannerID,String productName)
    { 
        //create query result MAP : Key = String and Value = list of aggregate results.
        Map<string,List<AggregateResult>> prodQuarResult = new Map<string,List<AggregateResult>>();
        try{
        //Fetch Account and Salesplanner Id from the salesplanner.
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:SalesPlannerID ];
        List<AggregateResult> saldata;
        List<AggregateResult> saldata2; 
        List<String> prdList = productName.split(',');

        prodQuarResult = new Map<string,List<AggregateResult>>();
            //get sales data records for last year
        saldata = [SELECT CALENDAR_MONTH(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =last_year GROUP BY CALENDAR_MONTH(Date__c) order by CALENDAR_MONTH(Date__c) desc];
        prodQuarResult.put('Lastyear', saldata);
             //get sales data records for this year
        saldata2 = [SELECT CALENDAR_MONTH(Date__c), SUM(Doses_Month_0__c) FROM Sales_Data__c WHERE Account__c =: salesPlanner.Account_Sales_Planner__c and Name In:prdList and Date__c =this_year GROUP BY CALENDAR_MONTH(Date__c) order by CALENDAR_MONTH(Date__c) desc];    


        prodQuarResult.put('Thisyear', saldata2);
            if(Test.isRunningTest())
                integer i=1/0;
        }
        catch(exception ex){
            ApexDebugLogController.insertLog('HorizontalMonthlychartsDisplay', 'getMonthlyDataReverse', ex.getMessage(), ex.getLineNumber());
        }

        return prodQuarResult;
     


    }
}