SandBox-2/force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <label>Monthly Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Data__c/fields/IDSalesDataExt__c.field-meta.xml
<CustomField>
    <fullName>IDSalesDataExt__c</fullName>
    <description>Outlet/DR - Product# - ReportEndDate</description>
    <externalId>true</externalId>
    <label>IDSalesDataExt</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Production/force-app/main/default/objects/Sales_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Data__c/fields/Sales_Category__c.field-meta.xml
<CustomField>
    <fullName>Sales_Category__c</fullName>
    <label>Sales Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/classes/salesData_Tests.cls
@isTest
private class salesData_Tests {

    static testMethod void salesData_Helper_UnitTest(){
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;

        Product2 testProduct = new Product2();
        testProduct.Name = 'Test Product';
        insert testProduct;

        Custom_Setting__c testSetting = Custom_Setting__c.getInstance('salesData_Helper');
        if ( testSetting == null || testSetting.Id == null ){
            testSetting = new Custom_Setting__c(Name='salesData_Helper');
        }
        testSetting.boolean__c = true;
        upsert testSetting;

        test.startTest();
            Sales_Data__c testSalesData = new Sales_Data__c();
            testSalesData.Account__c = testAccount.Id;
            testSalesData.Product__c = testProduct.Id;
            testSalesData.Date__c = Date.newInstance(2017,5,1);
            testSalesData.Sales_Category__c = '2';
            testSalesData.Data_Source__c = 'DDD';
            testSalesData.IDSalesDataExt__c = 'TESTTEST-1705';
            insert testSalesData;
        test.stopTest();
    }
}