Production/force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>IMS Address</label>
    <type>TextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>IMS City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Account/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <externalId>true</externalId>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Account/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Account/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>IMS Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/Daily_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Vaxchora Sales Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vaxchora Sales Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Daily_Sales_Datas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Daily_Sales_Data__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/ShipTo_Information__c/ShipTo_Information__c.object-meta.xml
<CustomObject>
    <label>ShipTo Information</label>
    <nameField>
        <label>ShipTo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShipTo Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ShipTo Informations</relationshipLabel>
    <relationshipName>ShipTo_Informations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/DDD_Outlet_ID__c.field-meta.xml
<CustomField>
    <fullName>DDD_Outlet_ID__c</fullName>
    <label>DDD Outlet ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/ShipTo_Information__c/fields/IsDelete__c.field-meta.xml
<CustomField>
    <fullName>IsDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDelete</label>
    <type>Checkbox</type>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship To</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SandBox-2/force-app/main/default/objects/ShipTo_Information__c/fields/ShipTo_Type__c.field-meta.xml
<CustomField>
    <fullName>ShipTo_Type__c</fullName>
    <label>ShipTo Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/classes/Shiptodatatest.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: Test Class for Shiptodata class.
* @Change:  
* @last modify by:   Archie Bisen
* @last modify date:  9-Jan-2020
* *************************************************************** */
@isTest
public class Shiptodatatest {
   
      public static testMethod void createAcc()
    {
        //create a record for acccount
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        
        insert acc;
         //create a record for Daily_Sales_Data__c
        Daily_Sales_Data__c ds = new  Daily_Sales_Data__c();
        ds.Name ='Test 2019';
        ds.ShipTo_Type__c= 'Direct';
        ds.DDD_Outlet_ID__c= '23456788';
        ds.Account__c = acc.id;
        insert  ds;
         //create a record for ShipTo_Information__c
        ShipTo_Information__c st = new ShipTo_Information__c();
        st.Name ='Test 2019';
        st.Account__c = acc.id;
        st.ShipTo_Type__c ='Direct';
        st.DDD_Outlet_ID__c = '23456788';
        insert  st;
        //Execution of fetchDailysalesData and fetchDailysalesData1 methods by passing the values.
        Test.startTest();
       
        Shiptodata.fetchDailysalesData(acc.id,5,5,'1');
        Shiptodata.fetchDailysalesData1(acc.id,5,5,'2');
      Shiptodata.fetchAllDailysalesData(acc.id);
        Shiptodata.fetchDailysalesData1(acc.id,5,5,'1');
        Shiptodata.fetchDailysalesData(acc.id,5,5,'2');
         String recId= acc.id;
         String recId1= acc.id;
        //Fetch the following data by executing the query
        List <Account> ac =  new List<Account>();
       ShipTo_Information__c[] si  =  [SELECT IsDelete__c, Id, Name, CreatedDate, CreatedById, LastModifiedDate,City__c,Country__c,State__c,Zip__c,
           													Address__c,Ship_To__c,LastModifiedById, DDD_Outlet_ID__c,ShipTo_Type__c, Account__c,Account__r.Name 
                                                          FROM ShipTo_Information__c where Account__c=: acc.Id AND IsDelete__c!= True Order by ShipTo_Type__c,LastModifiedDate];

        test.stopTest();
        
    }
    
    

}