Production/force-app/main/default/objects/Account/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <formula>Account_Sales_Planner__r.Outlet_Name__c</formula>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/classes/ContactsDisplaysTest.cls
@isTest
private class ContactsDisplaysTest {

     private static testMethod void createContact()
    {
        
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        insert acc;
        system.debug('Acc Id = '+acc.Id);
        
        Sales_Planner__c   sp = new  Sales_Planner__c();
        sp.Name ='Test Sp 2019';
        sp.Sales_Planner_Year__c='2019';
        sp.Account_Sales_Planner__c = acc.id;
        insert  sp;
        
        Contact cont = new Contact();
        cont.LastName='Test';
        cont.MobilePhone='1234567890';
        cont.Phone='123466789012';
        // cont.Account ='CARNEGIE MELLON UNIV';
        cont.Accountid= acc.id;
        insert cont;
        system.debug('::::cont.Accountid::::::'+cont.Accountid);
        System.debug(':::cont::::::;'+cont);
        
        Test.startTest();
        //ContactsDisplay cD=new ContactsDisplay();
        ContactsDisplays.getContacts(sp.id);
        Contact[] conn = [select Title,Phone,email,Name,Primary_Contact__c,Status__c,Contact_Relationship__c,Role__c from contact where accountid =: acc.id];
        system.debug('::::::::::conn:::::::::'+conn);
        system.assertEquals(1, conn.size());
        ContactsDisplays.getSalesPlanner(sp.id);
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:sp.id ];
        system.debug('::::::::::sp:::::::::'+salesPlanner);
        String result =ContactsDisplays.getIconName('Contact');
        
        test.stopTest();
        
    }
    
    private static testMethod void createContact1()
    {
        
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        insert acc;
        system.debug('Acc Id = '+acc.Id);
        
        Sales_Planner__c   sp = new  Sales_Planner__c();
        sp.Name ='Test Sp 2019';
        sp.Sales_Planner_Year__c='2019';
        sp.Account_Sales_Planner__c = acc.id;
        insert  sp;
        
        Contact cont = new Contact();
        cont.LastName='Test';
        cont.MobilePhone='1234567890';
        cont.Phone='123466789012';
        // cont.Account ='CARNEGIE MELLON UNIV';
        cont.Accountid= acc.id;
        insert cont;
        system.debug('::::cont.Accountid::::::'+cont.Accountid);
        System.debug(':::cont::::::;'+cont);
        
        Test.startTest();
        //ContactsDisplay cD=new ContactsDisplay();
        ContactsDisplays.getContacts(sp.id);
        Contact[] conn = [select Title,Phone,email,Name,Primary_Contact__c,Status__c,Contact_Relationship__c,Role__c from contact where accountid =: acc.id];
        system.debug('::::::::::conn:::::::::'+conn);
        system.assertEquals(1, conn.size());
        ContactsDisplays.getSalesPlanner(sp.id);
        Sales_Planner__c salesPlanner = [select id,Account_Sales_Planner__c from Sales_Planner__c where id =:sp.id ];
        system.debug('::::::::::sp:::::::::'+salesPlanner);
        String result =ContactsDisplays.getIconName('Sales_Planner__c');
        
        test.stopTest();
        
    }
    
}