Production/force-app/main/default/objects/Account/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <formula>Account_Sales_Planner__r.Outlet_Name__c</formula>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/X2019_TotalActivities__c.field-meta.xml
<CustomField>
    <fullName>X2019_TotalActivities__c</fullName>
    <label>CY Total Activities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/force-app/main/default/classes/Trg_Task_Test.cls
@isTest
private class Trg_Task_Test {
    
    private static testMethod void taskCreate()
    {     
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        insert acc;
        system.debug('Acc Id = '+acc.Id);
        
        Sales_Planner__c sp = new Sales_Planner__c();
        sp.Name='Test Account';
        sp.Sales_Planner_Year__c='2019';
        sp.Account_Sales_Planner__c = acc.id;        
        insert sp; 
        
        Sales_Planner__c spNew =[SELECT Name,X2019_TotalActivities__c FROM Sales_Planner__c WHERE Id=:sp.Id LIMIT 1];
        system.debug('::::::::::::acc:::::::::::'+sp);
        System.assertEquals(sp.Name,'Test Account');
        
        Task t1 = new Task();
        t1.subject='TestTask';
        //t1.Type='Phone Call';
        t1.WhatId=acc.Id;
        t1.status = 'Completed';
        t1.Product_Discussed__c = 'Vivotif';
        t1.Call_Stage__c ='Meaningful Dialogue';
        //t1.Call_Stage__c ='Closed/Not Viable';
        t1.description ='Disease/Product Introduction';
        //t1.Resources_Left__c = 'Vaxchora PI';
        t1.Resources_Left__c = 'IDSA Guide';
          
        t1.Closed_Reasons__c = 'Storage';
        
        Test.startTest();
        
        insert t1;
        update t1;
        
        system.debug('insert'+t1);
        
        // System.assertEquals(accNew.X2019_Total_Activities__c,1);
        Sales_Planner__c newAcc = new Sales_Planner__c();
        newAcc.Name ='test Update Account';
        newAcc.Id= sp.Id;
        //insert newAcc;
      //t1.WhatId=newAcc.Id;
      //  update t1;
        
        
       Sales_Planner__c updateAcc = [select id,X2019_TotalActivities__c,(select id,status,Type,WhatId from Tasks where status='Completed' ) from Sales_Planner__c   where id =:sp.Id LIMIT 1];
       // System.assertEquals(1,updateAcc.X2019_Total_Activities__c);
        system.debug('::::::::::::updateAcc:::::::::::'+updateAcc);
        Delete t1;
        
        Test.stopTest();
    }
    
    
}