Production/force-app/main/default/objects/Account/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <formula>Account_Sales_Planner__r.Outlet_Name__c</formula>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/classes/AccounthistorycontrollerTest.cls
@isTest
private class AccounthistorycontrollerTest {
	
   
    
      private static testMethod void createTask()
    {
        
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        insert acc;
        system.debug('Acc Id = '+acc.Id);
        
        Sales_Planner__c   sp = new  Sales_Planner__c();
        sp.Name ='Test Sp 2019';
        sp.Sales_Planner_Year__c='2019';
        sp.Account_Sales_Planner__c = acc.id;
        insert  sp;
        
         Contact cont = new Contact();
        cont.LastName='Test';
        cont.MobilePhone='1234567890';
        cont.Phone='123466789012';
        // cont.Account ='CARNEGIE MELLON UNIV';
        cont.Accountid= acc.id;
        insert cont;
    
         /*User us = new User();
        us.Username = 'test@samp.com';
       us.Email = 'test@samp.com';
       us.Alias = 'tsamp';
       
       //us.UserRoleId = 'user_role_id_goes_here';
       //us.ProfileId = 'user_profile_id_goes_here';
        us.CommunityNickname = 'te';
       us.IsActive = false;
       insert us;*/
        
        
        Task t = new Task();
        t.Subject='Test';
        t.OwnerId= UserInfo.getUserId();
        t.ActivityDate= Date.newInstance(2019,04,01);
        t.Priority= 'Normal';
        t.Type= 'Email';
        t.Status= 'Completed';
        t.Description= 'this is for testing purpose';
        t.Resources_Left__c='None';
        t.Call_Stage__c='Adopting';
        // cont.Account ='CARNEGIE MELLON UNIV';
        t.WhoId= cont.id;
        insert t;
        system.debug('::::t.Accountid::::::'+t.Accountid);
        System.debug(':::t::::::;'+t);
        
      
        Test.startTest();
        //ContactsDisplay cD=new ContactsDisplay();
        Accounthistorycontroller.gettask(sp.id);
       
        Task[] ta = [select id,Subject,Description,WhoId,Who.Name, WhatId, What.Name, OwnerId,Owner.Name,CreatedById,CreatedBy.Alias, ActivityDate, Type, Status from Task where Status='Completed' AND accountid =: acc.id];
       // String formattedDate = string.valueOf(ta.ActivityDate.month())+'-'+string.valueOf(ta.ActivityDate.day())+'-'+string.valueOf(ta.ActivityDate.year());   

        Accounthistorycontroller.TaskWrapper tw = new Accounthistorycontroller.TaskWrapper(t);
        system.debug('::::::::::ta:::::::::'+ta);
        system.assertEquals(1, ta.size());
        test.stopTest();
        
    }
    
    
}