Production/force-app/main/default/objects/Account/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <label>Outlet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Account_Sales_Planner__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account_ID</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Name__c</fullName>
    <formula>Account_Sales_Planner__r.Outlet_Name__c</formula>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <formula>HYPERLINK( Account_Sales_Planner__r.Parent.Id , Account_Sales_Planner__r.Parent.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Account</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SandBox-2/force-app/main/default/classes/AccHierarchyApexTest.cls
/* ***************************************************************
* Owner/Modify by Name : Archie Bisen
* @description: AccHierarchyApexTest is used to provide test data for AccHierarchyApex for code coverage.
* @Change:  
* @last modify by:  Vivek A
* @last modify date:  10-Jan-2020
* *************************************************************** */
@isTest
private class AccHierarchyApexTest {
    /* ***************************************************************
* @description: calling function to pass test data to AccHierarchyApex class for code coverage
* @Change:
* *************************************************************** */
    private static testMethod void createAcc()
    {
        //insert test account data
        Account acc = new Account();
        acc.Name='Test24';
        acc.Outlet_Name__c = 'Test1';
        insert acc;
        
        Account acc1 = new Account();
        acc1.Name='Test25';
        acc1.Outlet_Name__c = 'Test1';
        acc1.ParentId= acc.id;
        insert acc1;
        
        //insert test salesplanner data related to test account created.
        Sales_Planner__c   sp = new  Sales_Planner__c();
        sp.Name ='Test Sp 2019';
        sp.Sales_Planner_Year__c='2020';
        sp.Account_Sales_Planner__c = acc.id;
        insert  sp;
        
        Test.startTest();
        //test salesplanner id is passed as paramater to getAccountId method of AccHierarchyApex class to get account id.
        AccHierarchyApex.getAccountId(sp.id);
        String spId= sp.id;
        String recId= acc.id;
        String recId1= sp.id;
        
        List <Account> ac =  new List<Account>();
        //retrieve Account Id of test salesplaner sp.
        spId =  [select id ,name,Account_Sales_Planner__c,Parent_Account__c,Account_ID__c from Sales_Planner__c where id =:spId LIMIT 1].Account_ID__c;
        //test salesplanner id is passed as paramater to findHierarchyData method of AccHierarchyApex class.
        AccHierarchyApex.findHierarchyData (recId1);
        //test account id is passed as paramater to GetUltimateParentId method of AccHierarchyApex class.
        AccHierarchyApex.GetUltimateParentId(recId);
        string queryString = 'select id ,name, ParentId from Account where Id =:recId LIMIT 1';
        
        test.stopTest();
        
    }
    
    
}