Production/force-app/main/default/objects/pvEmailBatchConf__mdt/pvEmailBatchConf__mdt.object-meta.xml
<CustomObject>
    <description>In pvEmailBatchConf to set all configuration data</description>
    <label>pvEmailBatchConf</label>
    <pluralLabel>pvEmailBatchConfs</pluralLabel>
</CustomObject>

Production/force-app/main/default/objects/pvEmailBatchConf__mdt/fields/EmailFormatMetadataQuery__c.field-meta.xml
<CustomField>
    <fullName>EmailFormatMetadataQuery__c</fullName>
    <label>EmailFormatMetadataQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/pvEmailBatchConf__mdt/fields/EventQuery__c.field-meta.xml
<CustomField>
    <fullName>EventQuery__c</fullName>
    <description>To get All Event records base on the criteria</description>
    <label>EventQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/pvEmailBatchConf__mdt/fields/SalesPlannerQuery__c.field-meta.xml
<CustomField>
    <fullName>SalesPlannerQuery__c</fullName>
    <description>Get All Sales Planner record based on the Account User ID</description>
    <label>SalesPlannerQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Production/force-app/main/default/objects/pvEmailBatchConf__mdt/fields/TaskQuery__c.field-meta.xml
<CustomField>
    <fullName>TaskQuery__c</fullName>
    <description>Get all Task record based on the criteria</description>
    <label>TaskQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SandBox-2/force-app/main/default/objects/pvEmailBatchConf__mdt/fields/UserQuery__c.field-meta.xml
<CustomField>
    <fullName>UserQuery__c</fullName>
    <description>Get All User records based on the RAM User profile ID</description>
    <label>UserQuery</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Production/force-app/main/default/objects/pvSalesPlannerEmailFormats__mdt/pvSalesPlannerEmailFormats__mdt.object-meta.xml
<CustomObject>
    <description>SalesPlanner Email format for the reminder</description>
    <label>pvSalesPlannerEmailFormat</label>
    <pluralLabel>pvSalesPlannerEmailFormats</pluralLabel>
</CustomObject>

Production/force-app/main/default/objects/Sales_Planner__c/Sales_Planner__c.object-meta.xml
<CustomObject>
    <label>Sales Planner</label>
    <nameField>
        <label>Sales Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesPlanners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <formula>Account_Sales_Planner__r.Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Account_Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Account_Sales_Planner__c</fullName>
    <inlineHelpText>Don&#39;t change the Account Name from the Sales planner page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesPlanners</relationshipLabel>
    <relationshipName>SalesPlanners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner__c</fullName>
    <formula>(Account_Sales_Planner__r.Name) &amp;&quot; &quot;&amp;  TEXT(Sales_Planner_Year__c)</formula>
    <label>Sales Planner</label>
    <type>Text</type>
</CustomField>

SandBox-2/force-app/main/default/objects/Sales_Planner__c/fields/Sales_Planner_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Planner_Year__c</fullName>
    <label>Sales Planner Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/force-app/main/default/objects/Sales_Planner__c/fields/Untouched_Days__c.field-meta.xml
<CustomField>
    <fullName>Untouched_Days__c</fullName>
    <formula>Today()-DATEVALUE(LastModifiedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Untouched Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SandBox-2/force-app/main/default/classes/SalesPlannerEmailHelperTest.cls
@isTest
public class SalesPlannerEmailHelperTest 
{    
    @isTest
    public static void SalesPlannerEmailHelperTestAllCondition()
    {
        String iOwnerID = '005610000020lCoAAI';
        //Dummy Data addition code
        //
        Account pAcc = new Account(Name='Parent TestAcc');
        insert pAcc;
        
        List<Account> lstAcc = new List<Account>();
        for (Integer i=1;i<=6;i++){
            Account a = new Account(Name='TestAcc-' + string.valueOf(i), OwnerId = iOwnerID, ParentId = pAcc.Id);
            lstAcc.add(a);
        }
        insert lstAcc;
        
        List<Sales_Planner__c> lstSP = new List<Sales_Planner__c>();
        for (Integer i=1;i<=6;i++){
            
            Sales_Planner__c sp = new Sales_Planner__c(Name='zensarTest-' + string.valueOf(i) ,Sales_Planner_Year__c='2019',
                                                       Account_Sales_Planner__c=lstAcc[i-1].Id);
            lstSP.add(sp);
        }
        insert lstSP;
        
        List<Task> lstTask = new List<Task>();
        List<Event> lstEvent = new List<Event>();
        
        List<Sales_Planner__c> splist = [select id,Account_Sales_Planner__c,name,Sales_Planner_Year__c,
                                         Account_Sales_Planner__r.OwnerId,Untouched_Days__c,Account_Owner__c from Sales_Planner__c where Id in: lstSP];
        for (Integer i=0;i<splist.size();i++){
            if (i==0 || i==2 || i==4 || i==6){
                system.debug('Each Record values : '+ splist[i]);
                Task newTask = new Task(CreateEventWhenTaskCreated__c = true,Status='Open',Subject='Test task-' + i,
                                        ActivityDate = system.today().addDays(-65*(i+1)),whatId = splist[i].Id,OwnerId=iOwnerID, type='In Person',
                                        ActivityDateTime__c=system.today().addDays(-65*(i+1)),TaskSalesplannerDetails__c='Address');
                lstTask.add(newTask);
            }
            else{
                DateTime eDate = system.today().addDays(-8*(i+1));
                eDate = eDate.addMinutes(60);
                
                Event nEvent = new Event(Subject='Test Event -' + i,
                                         StartDateTime = system.today().addDays(-8*(i+1)),  type='In Person',
                                         EndDateTime = eDate,
                                         whatId = splist[i].Id, OwnerId=iOwnerID);
                lstEvent.add(nEvent);
            }            
        }
        
        for (Integer i=0;i<splist.size();i++){
                system.debug('Each Record values : '+ splist[i]);
                Task newTask = new Task(CreateEventWhenTaskCreated__c = true,Status='Open',Subject='Test task-' + i,
                                        ActivityDate = system.today().addDays(-75*(i+1)),whatId = splist[i].Id,OwnerId=iOwnerID, type='Email',
                                        ActivityDateTime__c=system.today().addDays(-75*(i+1)),TaskSalesplannerDetails__c='Address');
                lstTask.add(newTask);
        }
        
        insert lstTask;        
        insert lstEvent;
        
        //******************************************        
        
        // global variables
        List<pvEmailBatchConf__mdt> b_EmailBatchConf =  Database.query(System.Label.pvEmailBatchConfQuery);
        List<User> b_UserList;
        List<Sales_Planner__c> b_SPList;
        List<Task> b_TaskList;
        List<Event> b_EventList;
        List<pvSalesPlannerEmailFormats__mdt> b_EmailFormatMetaData;
        //List<csvBatchFormat> b_CsvBatchFormat =  new List<csvBatchFormat>();
        List<Messaging.SingleEmailMessage> b_EmailList = new List<Messaging.SingleEmailMessage>();
        
        //Get User List
        b_UserList = Database.query(b_EmailBatchConf[0].UserQuery__c);
        //***********************************************************
        //Start : Getting UserIDs in string 
        //***********************************************************
        String userID ='';
        Integer c = 0;
        Integer cTotal = b_UserList.size();
        for (User u : b_UserList){
            c++;
            userID += '\'' + u.Id + '\'' + (c<ctotal ? ',':'');
        }
        System.debug('userID :' + userID +' End');
        //***********************************************************
        //End : Getting UserIDs in string 
        //***********************************************************
        
        String spQuery = b_EmailBatchConf[0].SalesPlannerQuery__c;
        spQuery = spQuery.replace('##USERIDS##',userID);
        System.debug('spQuery :' + spQuery);
        System.debug('TaskQuery__c :' + b_EmailBatchConf[0].TaskQuery__c);
        System.debug('EventQuery__c :' + b_EmailBatchConf[0].TaskQuery__c);
        System.debug('EmailFormatMetadataQuery__c :' + b_EmailBatchConf[0].EmailFormatMetadataQuery__c);
        
        b_SPList = Database.query(spQuery);
        
        b_TaskList = Database.query(b_EmailBatchConf[0].TaskQuery__c);
        b_EventList = Database.query(b_EmailBatchConf[0].EventQuery__c);
        b_EmailFormatMetaData = Database.query(b_EmailBatchConf[0].EmailFormatMetadataQuery__c);
        
        
        Messaging.sendEmail(b_EmailList);
        //******************************************
        
        system.Test.startTest();
        b_EmailList = SalesPlannerEmailHelper.setEmailsToSPOwnerAndManager(b_SPList, b_UserList, b_TaskList, b_EventList, b_EmailFormatMetaData,b_EmailBatchConf );
        system.Test.stopTest();
    }
}